### ISSUE TITLE
Can the browser "back" call during RcsbFV3DCustom.unmount be optional?

### ISSUE THREAD

**Issue by cyrus0824** [rcsb/rcsb-saguaro-3d#3]
There is a [browser back call](https://github.com/rcsb/rcsb-saguaro-3d/blob/master/src/RcsbFv3D/RcsbFv3DAbstract.tsx#L59) during the [RcsbFV3DCustom.unmount call](https://rcsb.github.io/rcsb-saguaro-3d/classes/RcsbFv3DCustom.RcsbFv3DCustom-1.html#unmount).  Is there any way this could be optional?

**Comment by bioinsilico** [comment]
Thank you, @cyrus0824, for reporting that. I have fixed this issue, and it should not happen in v1.3.5. Please, let me know if you have any problems.

**Comment by cyrus0824** [comment]
Thank you so much for your prompt response 👍 

This is great.
