### ISSUE TITLE
Specifying the first displayed entity/chain in molstar using labelAsymId?

### ISSUE THREAD

**Issue by cyrus0824** [rcsb/rcsb-saguaro-3d#4]
Hi @bioinsilico, continuing from before:

Is there a way to specify the sequence loaded into the molstar sequence panel (for example by labelAsymId) on startup?

I saw that there was a [params](https://rcsb.github.io/rcsb-saguaro-3d/interfaces/RcsbFv3DAssembly._internal_.LoadParams.html#params) and a [props](https://rcsb.github.io/rcsb-saguaro-3d/modules/RcsbFv3DAssembly._internal_.html#PresetProps) that seem to pass values to the molstar init, but I don't see any options that might relate to setting the initial state (e.g. chain, entity, etc) on the sequence pane.

Do you have any advice?

Thanks for your help

**Comment by bioinsilico** [comment]
Hi @cyrus0824! I am not sure if I understand your question. The sequence loaded into molstar is defined by the PDB entry. Please, could you elaborate on your question?

**Comment by bioinsilico** [comment]
Hi @cyrus0824! Is any progress on this ticket?

**Comment by bioinsilico** [comment]
Hi @cyrus0824, I will close this ticket. But please feel free to reopen it if convenient.
