### ISSUE TITLE
CDN examples errors on page load

### ISSUE THREAD

**Issue by VryCafn8d** [rcsb/rcsb-saguaro-3d#6]
It looks like the example files under /cdn-examples may be out-of-date with the latest CDN release. When I attempt to run the single-chain example I receive a pair of errors. One is related to the Mol* interface's loadParams. It looks like pdbId has been changed to entryId: https://rcsb.github.io/rcsb-saguaro-3d/interfaces/RcsbFv3DAssembly._internal_.LoadParams.html.

var molstarConfig = {
    loadConfig: {
        loadMethod: "loadPdbIds",
        loadParams: [{
            pdbId: "1ash",
            id: "1ash_model"
        }]
    },

needs to be:

var molstarConfig = {
    loadConfig: {
        loadMethod: "loadPdbIds",
        loadParams: [{
            entryId: "1ash",
            id: "1ash_model"
        }]
    },

The other error appears to be related to the RcsbFvSelectorManager: RcsbFvSelectorManager.  It looks like an additional layer has been added to the object, so that index.js lines 90-91 need to be updated:

current:
        structureSelectionCallback: function (plugin, pfv, selection) {
        var sel = selection.getSelectionWithCondition("1ash_model", "A", "select");
should be:
        structureSelectionCallback: function (plugin, pfv, selection) {
        var sel = selection.selectionState.getSelectionWithCondition("1ash_model", "A", "select");

I believe there are likely other errors related to the RcsbFvSelectorManager elsewhere in the file as well. It would be extremely helpful to have these two example files working, since they've been useful references in the past.

**Comment by bioinsilico** [comment]
Thank you, @VryCafn8d. The CDN examples should be fully working now. Please, report any bugs or inconsistencies.

**Comment by bioinsilico** [comment]
@VryCafn8d, I will close this issue. But please feel free to reopen it if you find any other bugs.
