### ISSUE TITLE
How to switch chains by code

### ISSUE THREAD

**Issue by hi-asan** [rcsb/rcsb-saguaro-3d#7]
I complete the rendering of the page through RcsbFv3D.assembly, and get the chain collection through onChangeCallback. Now I want to switch chain[A,B,C,D] through code. can you tell me how to do

**Comment by bioinsilico** [comment]
Thank you, @hi-asan, for your question. Is this to display a specific chain when the structure is loaded?

**Comment by hi-asan** [comment]
![image](https://github.com/rcsb/rcsb-saguaro-3d/assets/12293038/882ed8c7-13f2-46f5-888c-50e85a134bd4)
![image](https://github.com/rcsb/rcsb-saguaro-3d/assets/12293038/3bc59138-9648-495f-9ad8-74b17284e0fa)



I tried to update the title but couldn't update it, I want to switch chain by updating the configuration
![image](https://github.com/rcsb/rcsb-saguaro-3d/assets/12293038/7e1851ec-3b93-49c9-a114-1fa826f3692c)



for example
```js
onChainChange(e){
           //to change chain
           //It has the same effect as the built-in selection ABCD
}
```

**Comment by hi-asan** [comment]
@bioinsilico Thank you very much, I will also study this issue in the future, if there is any result, I will reply here and hope to help you

**Comment by hi-asan** [comment]
If I can configure this content in RcsbFv3d. assembly, it will solve this problem
![image](https:github.com/rcsb/rcsb-saguaro-3d/assets/12293038/d50d323e-9346-41eb-8c85-7fc6187208d0)
